### ISSUE TITLE
前端热更新报错：compilation.getPathWithInfo is not a function

### ISSUE THREAD

**Issue by MJingv** [keenwon/Egg-Webpack-Starter#2]
2019-12-26 18:25:14,117 ERROR 71940 nodejs.TypeError: compilation.getPathWithInfo is not a function
at compilation.hooks.additionalChunkAssets.tap (/Users/pri/Egg-Webpack-Starter/node_modules/webpack/lib/HotModuleReplacementPlugin.js:287:26)
at SyncHook.eval [as call] (eval at create (/Users/pri/Egg-Webpack-Starter/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
  at SyncHook.lazyCompileHook (/Users/pri/Egg-Webpack-Starter/node_modules/tapable/lib/Hook.js:154:20)
  at hooks.optimizeTree.callAsync.err (/Users/pri/Egg-Webpack-Starter/node_modules/webpack-tool/node_modules/webpack/lib/Compilation.js:1299:37)
  at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pri/Egg-Webpack-Starter/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/pri/Egg-Webpack-Starter/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/Users/pri/Egg-Webpack-Starter/node_modules/webpack-tool/node_modules/webpack/lib/Compilation.js:1242:27)
    at hooks.make.callAsync.err (/Users/pri/Egg-Webpack-Starter/node_modules/webpack-tool/node_modules/webpack/lib/Compiler.js:550:17)
    at _err0 (eval at create (/Users/pri/Egg-Webpack-Starter/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
      at _addModuleChain (/Users/pri/Egg-Webpack-Starter/node_modules/webpack-tool/node_modules/webpack/lib/Compilation.js:1093:12)
      at processModuleDependencies.err (/Users/pri/Egg-Webpack-Starter/node_modules/webpack-tool/node_modules/webpack/lib/Compilation.js:1005:9)
      at process._tickCallback (internal/process/next_tick.js:61:11)

      pid: 71940
      hostname: localhost

前端改了文字就成这样了
====

**Comment by MJingv** [comment]
老哥 还维护不？ 看看呀@keenwon

**Comment by keenwon** [comment]
把 `package.json` 里的 webpack，固定在 4.28.4。删除 `node_modules` 和 `package-lock.json`，重新安装。

**Comment by MJingv** [comment]
> 把 `package.json` 里的 webpack，固定在 4.28.4。删除 `node_modules` 和 `package-lock.json`，重新安装。

不行，一样的报错。

我的操作是：/Users/pri/Egg-Webpack-Starter/client/src/views/Home.jsx 改动里面的内容并保存

**Comment by keenwon** [comment]
> 把 `package.json` 里的 webpack，固定在 4.28.4。删除 `node_modules` 和 `package-lock.json`，重新安装。

经过测试，此方法有效，如果你还有问题，请提供一个可复现的仓库

**Comment by keenwon** [comment]
https://github.com/keenwon/Egg-Webpack-Starter/commit/55deaecaa8106b8d0000cc6fb8f7b9097f63cacf

**Comment by MJingv** [comment]
> [55deaec](https://github.com/keenwon/Egg-Webpack-Starter/commit/55deaecaa8106b8d0000cc6fb8f7b9097f63cacf)

可以解决。感谢
