### ISSUE TITLE
npm run start 报错 

### ISSUE THREAD

**Issue by MJingv** [keenwon/Egg-Webpack-Starter#3]
操作
===
npm run build
npm run start

报错信息
===

```js
0 info it worked if it ends with ok
  1 verbose cli [ '/Users/.nvm/versions/node/v10.12.0/bin/node',
  1 verbose cli   '/Users/.nvm/versions/node/v10.12.0/bin/npm',
  1 verbose cli   'run',
  1 verbose cli   'start' ]
2 info using npm@6.11.2
3 info using node@v10.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle egg-webpack-starter@1.0.0~prestart: egg-webpack-starter@1.0.0
6 info lifecycle egg-webpack-starter@1.0.0~start: egg-webpack-starter@1.0.0
7 verbose lifecycle egg-webpack-starter@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle egg-webpack-starter@1.0.0~start: PATH: /Users/.nvm/versions/node/v10.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/pro/Egg-Webpack-Starter/node_modules/.bin:/Users/.nvm/versions/node/v10.12.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle egg-webpack-starter@1.0.0~start: CWD: /Users/pro/Egg-Webpack-Starter
10 silly lifecycle egg-webpack-starter@1.0.0~start: Args: [ '-c', 'egg-scripts start --daemon' ]
11 silly lifecycle egg-webpack-starter@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle egg-webpack-starter@1.0.0~start: Failed to exec start script
13 verbose stack Error: egg-webpack-starter@1.0.0 start: `egg-scripts start --daemon`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/.nvm/versions/node/v10.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/.nvm/versions/node/v10.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid egg-webpack-starter@1.0.0
15 verbose cwd /Users/pro/Egg-Webpack-Starter
16 verbose Darwin 18.7.0
17 verbose argv "/Users/.nvm/versions/node/v10.12.0/bin/node" "/Users/.nvm/versions/node/v10.12.0/bin/npm" "run" "start"
18 verbose node v10.12.0
19 verbose npm  v6.11.2
20 error code ELIFECYCLE
21 error errno 1
22 error egg-webpack-starter@1.0.0 start: `egg-scripts start --daemon`
22 error Exit status 1
23 error Failed at the egg-webpack-starter@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit 
```

**Comment by keenwon** [comment]
```shell
# 启动应用
npm start

# 停止应用
npm stop
```

start 是模拟服务器部署的，如果已经 start 过，先 stop

**Comment by MJingv** [comment]
> ```shell
> # 启动应用
> npm start
> 
> # 停止应用
> npm stop
> ```
> 
> start 是模拟服务器部署的，如果已经 start 过，先 stop

前后端开发的时候 npm run dev
前端开发完成 npm run build
prod服务器启动 npm run start&stop 

可能是 npm run dev 的时候kill master 没有结束就start导致这个问题吗？

**Comment by keenwon** [comment]
不确定，具体产生原因要看你怎么操作的
问题本质就是上次启动的没停掉，又启动了一次

**Comment by MJingv** [comment]
> 不确定，具体产生原因要看你怎么操作的
> 问题本质就是上次启动的没停掉，又启动了一次

好的，感谢
