### ISSUE TITLE
UglifyJs打包报错

### ISSUE THREAD

**Issue by MJingv** [keenwon/Egg-Webpack-Starter#5]
npm run build vendor报错

```
0 info it worked if it ends with ok
  1 verbose cli [ '/Users/.nvm/versions/node/v10.12.0/bin/node',
  1 verbose cli   '/Users/.nvm/versions/node/v10.12.0/bin/npm',
  1 verbose cli   'run',
  1 verbose cli   'build' ]
2 info using npm@6.11.2
3 info using node@v10.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle egg-webpack-starter@1.0.0~prebuild: egg-webpack-starter@1.0.0
6 info lifecycle egg-webpack-starter@1.0.0~build: egg-webpack-starter@1.0.0
7 verbose lifecycle egg-webpack-starter@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle egg-webpack-starter@1.0.0~build: PATH: /Users/.nvm/versions/node/v10.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/pri/wc-fe/node_modules/.bin:/Users/.nvm/versions/node/v10.12.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/pri/wc-fe/node_modules/.bin
9 verbose lifecycle egg-webpack-starter@1.0.0~build: CWD: /Users/pri/wc-fe
10 silly lifecycle egg-webpack-starter@1.0.0~build: Args: [ '-c',
  10 silly lifecycle   'rimraf ./app/public/static && NODE_ENV=production webpack' ]
11 silly lifecycle egg-webpack-starter@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle egg-webpack-starter@1.0.0~build: Failed to exec build script
13 verbose stack Error: egg-webpack-starter@1.0.0 build: `rimraf ./app/public/static && NODE_ENV=production webpack`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/Users/.nvm/versions/node/v10.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
  13 verbose stack     at EventEmitter.emit (events.js:182:13)
  13 verbose stack     at ChildProcess.<anonymous> (/Users/.nvm/versions/node/v10.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    13 verbose stack     at ChildProcess.emit (events.js:182:13)
    13 verbose stack     at maybeClose (internal/child_process.js:962:16)
    13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
    14 verbose pkgid egg-webpack-starter@1.0.0
    15 verbose cwd /Users/pri/wc-fe
    16 verbose Darwin 18.7.0
    17 verbose argv "/Users/.nvm/versions/node/v10.12.0/bin/node" "/Users/.nvm/versions/node/v10.12.0/bin/npm" "run" "build"
    18 verbose node v10.12.0
    19 verbose npm  v6.11.2
    20 error code ELIFECYCLE
    21 error errno 2
    22 error egg-webpack-starter@1.0.0 build: `rimraf ./app/public/static && NODE_ENV=production webpack`
    22 error Exit status 2
    23 error Failed at the egg-webpack-starter@1.0.0 build script.
    23 error This is probably not a problem with npm. There is likely additional logging output above.
    24 verbose exit [ 2, tru
```

**Comment by MJingv** [comment]
"uglifyjs-webpack-plugin": "1.3.0"
固定一下版本  https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/363
@keenwon

**Comment by keenwon** [comment]
> "uglifyjs-webpack-plugin": "1.3.0"
> 固定一下版本 [webpack-contrib/uglifyjs-webpack-plugin#363](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/363)
> @keenwon

改用 terser 吧
